TeamGalacticraft/Galacticraft

- src/main/java/io/github/teamgalacticraft/galacticraft/Galacticraft.java
- src/main/java/io/github/teamgalacticraft/galacticraft/blocks/GalacticraftBlocks.java
- src/main/java/io/github/teamgalacticraft/galacticraft/blocks/SiliconOreBlock.java
Split up and ported "block_basic_core"
* Tin decoration block
* Tin wall block
* Copper ore
* Tin ore
* Aluminum ore
* Silicon ore
* Copper block
* Tin block
* Aluminum block
* Silicon block
(Nothing has textures yet.)
Note: Can I have write access? (So I don't have to make these PRs)
> Port "block_basic_core"

- CODE_OF_CONDUCT.md
> Github suggested this 🅱️

- src/main/java/io/github/teamgalacticraft/galacticraft/blocks/machines/coalgenerator/CoalGeneratorContainer.java
This could probably be done in a cleaner way.
> Fix a compile error with containers.

- src/main/java/io/github/teamgalacticraft/galacticraft/blocks/machines/coalgenerator/CoalGeneratorBlock.java
- src/main/java/io/github/teamgalacticraft/galacticraft/blocks/machines/coalgenerator/CoalGeneratorBlockEntity.java
So it should work correctly now, although I haven't tested yet.
> Fix the way that some attributes are handled.

- src/main/java/com/hrznstudio/galacticraft/entity/GalacticraftEntityTypes.java
> made entities work

- src/main/java/com/hrznstudio/galacticraft/server/command/GalacticraftCommands.java
~~I fixed the implementation of you being teleported beneath bedrock when running the command and teleporting to the moon.~~
~~However, teleporting on the X and Z is broken.~~
This is now working without any problems.
> FIX: The /dimensiontp command now works properly

- README.md
> Chore: update README to reflect new repository URL

- README.md
~~shoot~~
Didn't know the Addon API changed its name woops
> Chore: fix README part two: electric boogaloo

- src/main/java/dev/galacticraft/mod/client/render/MoonSkyProperties.java
- src/main/java/dev/galacticraft/mod/mixin/BaseFluidMixin.java
- src/main/java/dev/galacticraft/mod/mixin/client/WorldRendererMixin.java
> fix: remove unnecessary redirect, narrow down other one

- src/main/java/dev/galacticraft/mod/world/gen/carver/CraterCarver.java
- src/main/java/dev/galacticraft/mod/world/gen/carver/GalacticraftCarver.java
- src/main/java/dev/galacticraft/mod/world/gen/chunk/MoonChunkGenerator.java
- src/main/resources/data/galacticraft/worldgen/biome/moon_highlands.json
- src/main/resources/data/galacticraft/worldgen/biome/moon_highlands_edge.json
- src/main/resources/data/galacticraft/worldgen/biome/moon_mare.json
- src/main/resources/data/galacticraft/worldgen/biome/moon_mare_edge.json
- src/main/resources/data/galacticraft/worldgen/configured_carver/moon_crater.json
Craters actually generate now and use a carver
> feat: moon craters

- .github/workflows/pr_check.yml
> fix: run actions when PRs are opened

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE/bug_fix.md
- .github/PULL_REQUEST_TEMPLATE/feature.md
- .github/workflows/build.yml
- .github/workflows/pr_check.yml
1. Improves templates for Bug Reports and Feature Request issues.
2. Adds templates for Bug Fix and Feature Implementation pull requests.
3. Adds CodeQL checks to workflows.
CodeQL runs checks for common code vulnerabilities when building.
> chore: GitHub improvements

- .gitignore
- build.gradle.kts
- gradle.properties
- src/gametest/java/dev/galacticraft/mod/gametest/GalacticraftTestSuite.java
- src/gametest/resources/fabric.mod.json
- src/main/java/dev/galacticraft/mod/api/block/FluidLoggable.java
- src/main/java/dev/galacticraft/mod/block/decoration/GratingBlock.java
- src/main/java/dev/galacticraft/mod/block/special/walkway/PipeWalkway.java
- src/main/java/dev/galacticraft/mod/block/special/walkway/WalkwayBlock.java
- src/main/java/dev/galacticraft/mod/block/special/walkway/WireWalkway.java
- src/main/java/dev/galacticraft/mod/client/gui/screen/ingame/SpaceRaceScreen.java
Adds pipe and wire network connection/disconnection tests and a grating flow test
> Implement gametest system

- .github/workflows/codeql.yml
- .github/workflows/pr_check.yml
- .github/workflows/publish.yml
- build.gradle.kts
also switch to using distributions-cache-enabled for the ones i missed
> feat: switch to using creds for reposilite repo

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/pr_check.yml
- .github/workflows/publish.yml
> fix: don't bother setting the executable bit in actions

- src/main/resources/data/galacticraft/recipes/crafting_table/aluminum_nugget.json
- src/main/resources/data/galacticraft/recipes/crafting_table/decoration/dark/dark_decoration.json
- src/main/resources/data/galacticraft/recipes/crafting_table/decoration/dark/dark_decoration_slab.json
- src/main/resources/data/galacticraft/recipes/crafting_table/decoration/dark/dark_decoration_stairs.json
- src/main/resources/data/galacticraft/recipes/crafting_table/decoration/dark/dark_decoration_stairs_opposite.json
- src/main/resources/data/galacticraft/recipes/crafting_table/decoration/dark/dark_decoration_wall.json
- src/main/resources/data/galacticraft/recipes/crafting_table/desh_nugget.json
- src/main/resources/data/galacticraft/recipes/crafting_table/lead_nugget.json
- src/main/resources/data/galacticraft/recipes/crafting_table/machine/advanced_solar_panel.json
- src/main/resources/data/galacticraft/recipes/crafting_table/meteoric_nugget.json
- src/main/resources/data/galacticraft/recipes/crafting_table/thermal_padding_leggings.json
- src/main/resources/data/galacticraft/recipes/crafting_table/tin_nugget.json
- src/main/resources/data/galacticraft/recipes/crafting_table/titanium_nugget.json
Added recipes for Nuggets ,Advanced Solar Panel  and Dark Decoration (uses desh)
> fix: thermal leggings pattern + recipes

- build.gradle.kts
> build: Allow build on license violations for now

- src/main/java/dev/galacticraft/mod/api/pipe/impl/PipeNetworkImpl.java
- src/main/java/dev/galacticraft/mod/api/wire/impl/WireNetworkImpl.java
Resolves #257 
See [above issue](https://github.com/TeamGalacticraft/Galacticraft/issues/257#issuecomment-1678015422) for problem description.
This PR modifies `WireNetworkImpl` to fetch `Wire` objects from its own map instead of going to the world state. Doing it this way prevents chunks from being (re)loaded while the world is saving and shutting down, which was causing the infinite loop.
Applied the same approach to `PipeNetworkImpl` as pipe networks had the same issue.
> fix: Prevent infinite loop on world close caused by wires

- src/main/java/dev/galacticraft/mod/client/model/OxygenSealerSpriteProvider.java
- src/main/java/dev/galacticraft/mod/mixin/AbstractContainerMenuAccessor.java
- src/main/resources/assets/galacticraft/models/machine/circuit_fabricator.json
- src/main/resources/assets/galacticraft/models/machine/coal_generator.json
- src/main/resources/assets/galacticraft/models/machine/electric_compressor.json
- src/main/resources/assets/galacticraft/models/machine/oxygen_sealer.json
I fixed up all the machine panes so it is clear what configuration each machine is in.
> fix: Machine Panes

- src/main/java/dev/galacticraft/mod/content/block/special/rocketlaunchpad/RocketLaunchPadBlock.java
- src/main/java/dev/galacticraft/mod/content/entity/orbital/RocketEntity.java
addresses bugs #323 and #324. Also refactors code in RocketLaunchPadBlock.java to improve readability. Also adds a feature where the player will exit the rocket at ground level when dismounting instead of in the air (this was probably the intended behavior)
> fix: bugs pertaining to rocket 

- src/main/java/dev/galacticraft/mod/api/pipe/impl/PipeNetworkImpl.java
- src/main/java/dev/galacticraft/mod/api/wire/impl/WireNetworkImpl.java
- src/main/java/dev/galacticraft/mod/content/block/special/aluminumwire/tier1/AluminumWireBlock.java
- src/main/java/dev/galacticraft/mod/content/block/special/fluidpipe/GlassFluidPipeBlock.java
- src/main/java/dev/galacticraft/mod/content/block/special/fluidpipe/PipeBlockEntity.java
I have brought the fluid pipe functionality in line with the way wires are working.
> fix: Correcting the ways pipes connect

- src/main/java/dev/galacticraft/mod/api/block/MultiBlockMachineBlock.java
- src/main/java/dev/galacticraft/mod/content/block/machine/SimpleMultiBlockMachineBlock.java
Fixed issue https://github.com/TeamGalacticraft/Galacticraft/issues/333
This is my first time contributing to anything large and important like this, so apologies if I did something wrong.
> Made solar panel parts break when the base block breaks

- src/main/java/dev/galacticraft/mod/api/block/MultiBlockBase.java
- src/main/java/dev/galacticraft/mod/content/block/special/CryogenicChamberPart.java
- src/main/java/dev/galacticraft/mod/content/block/special/SolarPanelPartBlock.java
This fix ensures that Cryogenic Chambers and Solar Panels are fully removed when a part of them breaks.
Fixes issue https://github.com/TeamGalacticraft/Galacticraft/issues/350
> fix: made solar panel and cryogenic chamber base blocks break when a part breaks

- src/main/java/dev/galacticraft/impl/internal/mixin/oxygen/LevelMixin.java
- src/main/java/dev/galacticraft/mod/accessor/GCLevelAccessor.java
- src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java
- src/main/java/dev/galacticraft/mod/events/GCEventHandlers.java
- src/main/java/dev/galacticraft/mod/machine/SealerManager.java
- src/main/java/dev/galacticraft/mod/mixin/LevelMixin.java
- src/main/java/dev/galacticraft/mod/mixin/ServerLevelMixin.java
> fix: oxygen sealer mechanics
